### PR TITLE
Season ticket fix

### PR DESCRIPTION
**Pull request by WBGroupR**
These changes apply fixes to the season ticket code to make it conform to Google Java Style - as per previous review comments by Duane

### CODE REVIEW

**Review by duane-mcmahon — CHANGES_REQUESTED** [review]
SeasonTicket: TYPE. Fundamentals: Make class final if not being used for inheritance.  
Not implemented?

**Comment by WBGroupR** [comment]
Duane, where is that mentioned? Can’t see it in the Google Style Guide

**Comment by duane-mcmahon** [comment]
no i am working off this 
checklist: https://dzone.com/articles/java-code-review-checklist
google style infringements come under one of the catagories in that 
checklist.

**Comment by WBGroupR** [comment]
But that’s not working to the script - we’ve already decided to use the Google one haven’t we? Using that one would just confuse things (and probably add more effort in the long run)

**Comment by duane-mcmahon** [comment]
I accept your point. It's an interesting document - only a handful of 
the items in that checklist come up as potential issues for us in our 
case. I adopted it 'cos it gives greater coverage and consequently the 
review greater depth. Its not complicated, it's relevant, and serves our 
purpose well if adopted.
I believe it will be adopted at tomorrows meeting as part of the review. 
Jim emphasised in last night's chat that these reviews should be as 
'serious' as possible and as verbose as possible. 
Google style issues come up as a 'format' issue in that checklist.

**Comment by WBGroupR** [comment]
ok, but it’s just so late for us to be doing something different - assignment is due on coming Monday! And I have another assignment due  Wednesday. Also, the need to be verbose was why I was reticent to use the Google docs plug-in for IntelliJ because it would tend to automatically clean up all the issues, leaving us with nothing to catch in our reviews. When we first started doing these reviews I was concerned that we weren’t putting in many comments and just allowing anything to get approved. 

It’s all a bit bizarre because this process actually encourages you to make a lot of errors only because you then have something to comment on, where in practice we should be aiming to have clean code as much as possible. It probably would have been better for him to just give us all the code with lots of errors, so we then have to find errors and correct them or something.

Anyway, we can discuss this tomorrow I guess….

**Comment by duane-mcmahon** [comment]
I see your point. I applied the checklist for google style just the same 
in spite of the plugin and you can simply say flag pass/fail for each 
item. If it passes it passes! As long as the activity is visible I am 
sure it will satisfy requirements. Bear in mind that he will look at 
each members work individually in this regard. If members wish to go 
above and beyond a simple style check.
I am happy pass your code of course. We'll discuss tomorrow. As long as 
you feel as though you putting in the mooted number of hours for this 
unit each week i do not have a quarrel with you.
Regards!

**Comment by WBGroupR** [comment]
I can do that extra fix, not a problem as such, just need to delete the current branch and add/commit and re push to origin. Just want to be sure what set of guidelines we are working with - if it’s the Chopker one that’s fine, I will need to review it though to make sure my code passes everything else and we will need to make a link to it in our wiki...

W

**Review by navajo00 — DISMISSED** [review]

**Comment by WBGroupR** [comment]
Hi Chris, thanks, but I am confused because in GitHub is says that the pull request is still open and merging is blocked?

Wayne

**Comment by WBGroupR** [comment]
Need to confirm if this pull request is approved or code requires further refactoring.

**Pull request closed without merging**
