### PR TITLE
test for carpark class using mockito and junit

### PR DESCRIPTION
**Pull request by duane-mcmahon**
We don't jars in the lib folder; I updated the gitignore to exclude the mockito libary and dependencies.

### CODE REVIEW

**Comment by duane-mcmahon** [comment]
This pull request is for the test class for Carpark. It's not possible to test some of the items in the spec document in this iteration because the code tested was not written to align with the new 'revealed' requirement in the spec. In particular the method that calculates a charge is problematic.
In relation to the code review for this request, it has two parts. These parts are the test class and the class being tested. In relation to the Carpark class being tested, several of the tests identify defects in the Carpark class.
These defects include:

  @Override
    public void deregister(ICarparkObserver observer) {

        observers.remove(observer);
        numberOfCarsParked--;
    }

The method above is intended to register an observer which turns out to be an EntryController. Registering the controller does not impact upon the number of carparking places available and therefore
the last line in the method is not justified.

In relation to problems with the test code i have submitted for review,

The tests for registerSeasonTicket() and deregisterSeasonTicket() are failing. I am assuming that the test fails because the test is doing something incorrectly (are the mocked tickets instantiated incorrectly???):

  void registerSeasonTicket() {

        ISeasonTicket tkt = mock(SeasonTicket.class);

        testItem.registerSeasonTicket(tkt);

        assertEquals(true, testItem.isSeasonTicketInUse(tkt.getId()));
        
        try {

            testItem.registerSeasonTicket(new SeasonTicket("S9999", "Wrong Name", 0L, 0L));

            fail("Expected a RuntimeException to be thrown");

        } catch (Exception e) {

            assertEquals("Wrong carpark!", e.getMessage());
        }
    }

 void deregisterSeasonTicket() {

        ISeasonTicket tkt = mock(SeasonTicket.class);

        testItem.registerSeasonTicket(tkt);

        testItem.deregisterSeasonTicket(tkt);

        assertEquals(false, testItem.isSeasonTicketInUse(tkt.getId()));
    }

These fail with a NullPointerException at "sTicketRecs.next().getId().equals(ticket.getId())" below (in SeasonTicketDAO):

  @Override
  public void deregisterTicket(ISeasonTicket ticket) {

    Iterator<ISeasonTicket> sTicketRecs = seasonTickets.iterator();

    while (sTicketRecs.hasNext()) {

      if (sTicketRecs.next().getId().equals(ticket.getId())) {

        sTicketRecs.remove();
        break;
      }
    }
  }

Finally the test for  void getAdhocTicket() is problematic because the corresponding method encapsulates a call to adhocTicketDAO.findTicketByBarcode(barcode). The barcode is not a natural id; the underlying method should search for the ticket by ticket number. The test fails when only a single ticket has been issued (should pass!) but passes when more than one ticket has been issued. Unexplained at this point in time.

All knowledge welcome,
As Usual,
D.M.

**Review by WBGroupR — COMMENTED** [review]
Very difficult to comment on these commits as one would need to see test results as they happen and also unknown if specs are being tested or not.

Also, just a query: is the try..catch the best way to test the Carpark constructor or is there some JUnit expression that can be used?

I don't know what logger does (have never used it) - need to ask you about that.

**Comment by duane-mcmahon** [comment]
Yes, you run the test from the ide:

screenshot - 28_08_2017 9_26_22 am


I believe the try/catch e.g. 

 try {

            Carpark testitem = new Carpark("", 3, adhocTicketDAO, seasonTicketDAO);

            fail("Expected a RuntimeException to be thrown");

        } catch (Exception e) {

            assertEquals("Invalid argument passed to Carpark constructor.", e.getMessage());
        }

-this is one of several recommended ways to test for an exception. See:https://stackoverflow.com/questions/156503/how-do-you-assert-that-a-certain-exception-is-thrown-in-junit-4-tests

**Review by duane-mcmahon — COMMENTED** [review]
i'll pass them.

**Pull request merged**
